### ISSUE TITLE
DNS Crypt source not sound

### ISSUE THREAD

**Issue by Stretchster** [A3sal0n/FalconGate#50] opened 2018-01-29 19:20 UTC
Hi all, just trying to install Falcongate. I tried both from image and from scratch. I keep getting errors on the DNSCRYPT part of the install.  Is this something we can bypass in order to complete the install? Im not getting DHCP to work so I can login to the GUI and configure. Im assuming the DNSCrypt is culprit for not completing the install. Any help would be appreciated.

Thanks

**Comment by A3sal0n** [comment] 2018-01-29 20:29
Hi @Stretchster 

Thanks for reaching out. Could you share the details below so we can look into this and try to reproduce your issue?

- Hardware specs
- OS image and version
- A screenshot showing the error message from DNSCrypt

A side note: If you deploy our Raspbian image for RPi 3 from [here](https://github.com/A3sal0n/FalconGate/wiki/Downloads) you don't have to install anything else because FalconGate and all its dependencies are already installed.

**Comment by Stretchster** [comment] 2018-01-30 19:01
Hi A3sal0n, thanks for the link to the image that worked. I thought I did download it and tried but I was wrong :) One more question, I registered for the FalconGateAPI but did not receive a key. Is this something i will get emailed at a later date? Sorry for my newb questions and again thanks for your help.

**Comment by A3sal0n** [comment] 2018-01-30 21:24
Hi, I'm glad it worked this time!

It usually takes a while to receive the free key for our API because we do a manual revision of each request in our free time :)

Please feel free to ask any time, we will always answer as soon as possible and to the best of our knowledge.

**Comment by easy4MEr** [comment] 2018-02-20 13:12
DNSCrypt source have been moved by the authors to new location -> https://download.dnscrypt.info/dnscrypt-proxy/dnscrypt-proxy.zip

Editing of the install scripts is neccessary to fix this issue.

**Comment by A3sal0n** [comment] 2018-02-27 08:56
Thanks @easy4MEr for the heads up on this.
I found precompiled arm binaries that work with Raspbian and RPi in the link below.
https://github.com/jedisct1/dnscrypt-proxy/releases/download/2.0.4/dnscrypt-proxy-linux_arm-2.0.4.tar.gz
I propose to use this one to avoid unnecessary delays due to compilation.

**Comment by A3sal0n** [comment] 2018-02-27 21:27
This bug is now fixed

Thanks @Stretchster and @easy4MEr

**Closed by A3sal0n** 2018-02-27 21:27 UTC
Labels: bug, question
